### PR TITLE
Add bibtex block to citations

### PR DESCRIPTION
**Pull request by martinagvilas**

### CODE REVIEW

**Comment by datapythonista** [comment]
Very cool, thanks for taking care of it.

**Comment by datapythonista** [comment]
If you want to add:
```css
code {
    white-space: pre;
}
```
to the css file, the bib blocks will render correctly (we can leave that to the designer too.

Also, do you think have the name of the paper, the pdf link, and the bib block as items of a list adds value? difficult to tell without having styles in the page, but not sure if not having the list, and having the pdf link at the end of the paper name (e.g. `pandas, whatever, Wes McKinney [pdf]`) could be better.

Up to you, I think you're more used to cite papers than me :)

**Comment by martinagvilas** [comment]
You mean adding that line [here](https://github.com/datapythonista/pandas-web/blob/master/theme/static/css/pandas.css)? I could try it!

I will try putting directly the bibtex without list (and linking the pdf at the end of the line) and we can decide which looks better (at least without the desginer for now).

**Comment by datapythonista** [comment]
> You mean adding that line [here](https://github.com/datapythonista/pandas-web/blob/master/theme/static/css/pandas.css)? I could try it!

Yes, correct :)

**Comment by datapythonista** [comment]
I fixed a bit the styles, you can see it better now, I think without a list will look better: https://datapythonista.github.io/pandas-web/community/citing.html

**Comment by martinagvilas** [comment]
It looks better indeed! I will remove the list.

**Pull request merged**
