### PR TITLE
Added papers to cite

### PR DESCRIPTION
**Pull request by martinagvilas**
Added the papers suggested in this [page](https://pandas.pydata.org/talks.html)

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @martinagvilas, this is very useful

What do you think about adding a block with the bib entry, like scikit-learn does?

**Comment by martinagvilas** [comment]
Makes sense! Will work on it.

**Comment by martinagvilas** [comment]
Would it be better to add the bib entry in a separate block, like scikit-learn does, or provide a link to a downloadable bib, like in this [page](https://pandas.pydata.org/talks.html)

**Comment by datapythonista** [comment]
I like what scikit-learn does, but it's a question of preference, so I'm happy with whatever you decide. :)

**Pull request merged**
